apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
spec:
  ports:
  - name: http
    port: 8001
    targetPort: 80
  selector:
    app: ${APP_NAME}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
      version: v1
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        version: v1
    spec:
      containers:
      - image: ${IMAGE_NAME}
        imagePullPolicy: IfNotPresent
        name: ${APP_NAME}
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "2"
            memory: 1Gi
          requests:
            cpu: "10m"
            memory: 30Mi
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: ${INGRESS_NAME}
spec:
  rules:
    - host: ${INGRESS_HOST}
      http:
        paths:
          - path: /*
            backend:
              serviceName: ${APP_NAME}
              servicePort: 8001